### PR TITLE
ui-fixes-buttons

### PR DESCRIPTION
**Pull request by RupeshMangalam21**
Updated css styling for login and sign up buttons.

### CODE REVIEW

**Review by prince-panwar — CHANGES_REQUESTED** [review]
* Login button needs to be centred 
* Signup should be a link, not a button also centred below the login button
* Login form's size should be smaller 
*  Same goes for the signup form

**Comment by RupeshMangalam21** [comment]
> * Login button needs to be centred
> * Signup should be a link, not a button also centred below the login button
> * Login form's size should be smaller
> * Same goes for the signup form

Working on these already. Will commit in this pr.

**Comment by RupeshMangalam21** [comment]
A sign up button would look much better than a link.

**Review by RupeshMangalam21 — COMMENTED** [review]
All requested changes have been made. Except the responsiveness. That issue will be worked upon at later time.

**Pull request merged**
