### PR TITLE
I fixed all the imports and i fixed the btn

### PR DESCRIPTION
**Pull request by artenis-alija**
So in the code, I have done here I have fixed all the imports since none of them generally worked and I made the logo image a div with a background image, we can change the height and width if you would like just contact me, I also centered the logo, it looks currently more appealing but it can change as well.
I had to import sass into this project in order to change the color of the text and to change the text decoration.
For any more help please let me know. i would like to help more on this project.

### CODE REVIEW

**Comment by artenis-alija** [comment]
i added !important in main.sass otherwise it wont work

**Comment by artenis-alija** [comment]
with my three pushes, you can see the push that says fixed the footer to stay at the bottom you will have a code that in a nutshell will have the entire homepage looking very good. 
The logo is fine, the footer is fine, and the button has the color as requested. 
I hope i can help again the future.

**Comment by artenis-alija** [comment]
I have upgraded the look quite a lot in my last pull request, now there is no need to scroll in the page if there is a single page, and I fixed the logo to have the same margin on top and bottom in the navbar.

**Review by prince-panwar — CHANGES_REQUESTED** [review]
* Cards have become unresponsive to dimension changes in your branch. Please fix
* you need to update your local repo as there have been some major changes in file organisation and the code. 

thanks for contributing.

**Comment by artenis-alija** [comment]
Hi,
The issue with the cards was there in the beginning, I tried to solve the issues at hand.
I will see if I find the time to work on the other issue. I made many pushes for I made different looks and different solutions, you can choose which one you want to use and leave that one in the branch.

**Pull request closed without merging**
